# Single Country Script
# in first line, indicate the country code for the country of interest.
country.code<-"MWI"		#indicate ISO code for country

# A figure is generated by default.  If you set this to TRUE, then the figure will be 
# output as an .eps file -- and will not display on the screen
output.figure<-FALSE       

wd<-getwd()
require(MASS)
###################################################
### load-functions
###################################################
####################################################
# call all necessary functions and packages
source("datainput.R") # functions to process the data
source("Sfx.R") # functions to run the EKF
source("filtersmooth.R") # an accessory function for the EKF
source("ekf.optim.R") # a function to find the maximum likelihood
source("filtered_trans.R") # accessory functions to construct confidence intervals
source("estimate_incidence.R") # the function to return incidence estimates
source("estimate_mortality.R") # the function to return mortality estimates
source("read_sia.R")	# generate age-corrected SIA coverage
source("read_outbreaks.R")	# generate matrix of "outbreaks" or high reporting years
################################################
###################################################
###load-data
###################################################
allcases<-read.csv("input-cases.csv",header=T,row.names=1)
allbirths<-read.csv("input-births.csv",header=T,row.names=1)
alldeaths<-read.csv("input-deaths_5.csv",header=T,row.names=1)
allpop<-read.csv("input-populations.csv",header=T,row.names=1)
allmcv1<-read.csv("input-mcv1.csv",header=T,row.names=1)
mcv1.12mo<-read.csv("input-mcv1vaxeff.csv",header=T,row.names=1)
allmcv2<-read.csv("input-mcv2.csv",header=T,row.names=1)
allsia<-read.csv("output-sia_age_corrected.csv",header=T,row.names=1)
first.surveillance<-unlist(read.csv("input-first.surveillance.csv",header=T,row.names=1)[,2])
outbreaks<-read.csv("output-outbreaks.csv",header=T,row.names=1) 
###################################################
### estimate-incidence
###################################################
setwd(paste(wd,"/single country output/",sep=""))
ignore.indices<-which(!rownames(allcases)==country.code)
incidence_estimate(binary.file="output-incidence.Rdat", allcases, allbirths, alldeaths,
allpop, allmcv1, mcv1.12mo, allmcv2, allsia, first.surveillance, outbreaks, ignore.indices,
display=TRUE)
load("output-incidence.Rdat")
setwd(wd)
###################################################
### load-mortality-data
###################################################
agedist<-read.csv("input-agedist_pred.csv",header=T)
agedist.se<-read.csv("input-agedist_se.csv",header=T)
cfr1<-read.csv("input-cfr1-constant.csv",header=T,row.names=1) 
cfr2<-read.csv("input-cfr2-constant.csv",header=T,row.names=1)
cfr3<-read.csv("input-cfr3-constant.csv",header=T,row.names=1)
mcv_5<-read.csv("input-mcv1x5yrs.csv",header=T,row.names=1)
codes<-read.csv("input-gbd_Region.csv",header=T,row.names=1)
###################################################
### estimate-mortality
###################################################
setwd(paste(wd,"/single country output/",sep=""))
estimate_mortality(binary.file="output-mortality.Rdat",incidence_workspace="output-incidence.Rdat",agedist, agedist.se, cfr1,cfr2,cfr3, mcv_5, codes,ignore.indices, ITER=1000, display=TRUE)
load("output-mortality.Rdat")
setwd(wd)

###################################################
### check against all-cause childhood mortality and define new outbreak matrix
###################################################
igme<-read.csv("input-igme.csv",header=T,row.names=1)[,1:(dim(allcases)[2]-1)]
# here is where you would change the "outbreak cutoff" from .20 to .10, etc
outbreak.cutoff<-.35
outbreaks.new<-cbind(outbreaks[,1],!(is.na(outbreaks[,2:(dim(allcases)[2])]) | measles_deaths>(outbreak.cutoff*igme)))  #NOTE: this will produce a warning -- it is not a problem, it happens because there are "NA" entries in outbreak
outbreaks.new[outbreaks.new==F]<-NA
#outbreaks.new[,1:10]<-1
setwd(paste(wd,"/single country output/",sep=""))
write.table(outbreaks.new,file="output-outbreaks-new.csv",  sep=",",row.name=rownames(allcases),col.name=colnames(allcases))
setwd(wd)
######################################################################################################
######################################################################################################
### Re-run with the new outbreak matrix
######################################################################################################
######################################################################################################
######################################################################################################
### load-functions
###################################################
####################################################
# call all necessary functions and packages
source("datainput.R") # functions to process the data
source("Sfx.R") # functions to run the EKF
source("filtersmooth.R") # an accessory function for the EKF
source("ekf.optim.R") # a function to find the maximum likelihood
source("filtered_trans.R") # accessory functions to construct confidence intervals
source("estimate_incidence.R") # the function to return incidence estimates
source("estimate_mortality.R") # the function to return mortality estimates
################################################
###################################################
###load-data
###################################################
allcases<-read.csv("input-cases.csv",header=T,row.names=1)
allbirths<-read.csv("input-births.csv",header=T,row.names=1)
alldeaths<-read.csv("input-deaths_5.csv",header=T,row.names=1)
allpop<-read.csv("input-populations.csv",header=T,row.names=1)
allmcv1<-read.csv("input-mcv1.csv",header=T,row.names=1)
mcv1.12mo<-read.csv("input-mcv1vaxeff.csv",header=T,row.names=1)
allmcv2<-read.csv("input-mcv2.csv",header=T,row.names=1)
allsia<-read.csv("output-sia_age_corrected.csv",header=T,row.names=1)
first.surveillance<-unlist(read.csv("input-first.surveillance.csv",header=T,row.names=1)[,2])
outbreaks<-read.csv(paste(wd,"/single country output/output-outbreaks-new.csv",sep=""),header=T,row.names=1) # the new file -- updated from the step above
###################################################
### estimate-incidence
###################################################
setwd(paste(wd,"/single country output/",sep=""))
ignore.indices<-which(!rownames(allcases)==country.code)
incidence_estimate(binary.file="output-incidence.Rdat", allcases, allbirths, alldeaths,
allpop, allmcv1, mcv1.12mo, allmcv2, allsia, first.surveillance, outbreaks, ignore.indices,
display=TRUE)
load("output-incidence.Rdat")
setwd(wd)
###################################################
### load-mortality-data
###################################################
agedist<-read.csv("input-agedist_pred.csv",header=T)
agedist.se<-read.csv("input-agedist_se.csv",header=T)
cfr1<-read.csv("input-cfr1-constant.csv",header=T,row.names=1) 
cfr2<-read.csv("input-cfr2-constant.csv",header=T,row.names=1)
cfr3<-read.csv("input-cfr3-constant.csv",header=T,row.names=1)
mcv_5<-read.csv("input-mcv1x5yrs.csv",header=T,row.names=1)
codes<-read.csv("input-gbd_Region.csv",header=T,row.names=1)
###################################################
### estimate-mortality
###################################################
setwd(paste(wd,"/single country output/",sep=""))
estimate_mortality(binary.file="output-mortality.Rdat",incidence_workspace="output-incidence.Rdat",agedist, agedist.se, cfr1,cfr2,cfr3, mcv_5, codes,ignore.indices, ITER=10000, display=TRUE)
load("output-mortality.Rdat")
setwd(wd)
###################################################
### check against all-cause childhood mortality and define new outbreak matrix
###################################################
igme<-read.csv("input-igme.csv",header=T,row.names=1)[,1:(dim(allcases)[2]-1)]
# here is where you would change the "outbreak cutoff" from .20 to .10, etc
outbreak.cutoff<-.35
outbreaks.new<-cbind(outbreaks[,1],!(is.na(outbreaks[,2:(dim(allcases)[2])]) | measles_deaths>(outbreak.cutoff*igme)))  #NOTE: this will produce a warning -- it is not a problem, it happens because there are "NA" entries in outbreak
outbreaks.new[outbreaks.new==F]<-NA
#outbreaks.new[,1:10]<-1
setwd(paste(wd,"/single country output/",sep=""))
write.table(outbreaks.new,file="output-outbreaks-new.csv",  sep=",",row.name=rownames(allcases),col.name=colnames(allcases))
setwd(wd)

######################################################################################################
######################################################################################################
### Re-run with the new outbreak matrix
######################################################################################################
######################################################################################################
######################################################################################################
### load-functions
###################################################
####################################################
# call all necessary functions and packages
source("datainput.R") # functions to process the data
source("Sfx.R") # functions to run the EKF
source("filtersmooth.R") # an accessory function for the EKF
source("ekf.optim.R") # a function to find the maximum likelihood
source("filtered_trans.R") # accessory functions to construct confidence intervals
source("estimate_incidence.R") # the function to return incidence estimates
source("estimate_mortality.R") # the function to return mortality estimates
################################################
###################################################
###load-data
###################################################
allcases<-read.csv("input-cases.csv",header=T,row.names=1)
allbirths<-read.csv("input-births.csv",header=T,row.names=1)
alldeaths<-read.csv("input-deaths_5.csv",header=T,row.names=1)
allpop<-read.csv("input-populations.csv",header=T,row.names=1)
allmcv1<-read.csv("input-mcv1.csv",header=T,row.names=1)
mcv1.12mo<-read.csv("input-mcv1vaxeff.csv",header=T,row.names=1)
allmcv2<-read.csv("input-mcv2.csv",header=T,row.names=1)
allsia<-read.csv("output-sia_age_corrected.csv",header=T,row.names=1)
first.surveillance<-unlist(read.csv("input-first.surveillance.csv",header=T,row.names=1)[,2])
outbreaks<-read.csv(paste(wd,"/single country output/output-outbreaks-new.csv",sep=""),header=T,row.names=1) # the new file -- updated from the step above
###################################################
### estimate-incidence
###################################################
setwd(paste(wd,"/single country output/",sep=""))
ignore.indices<-which(!rownames(allcases)==country.code)
incidence_estimate(binary.file="output-incidence.Rdat", allcases, allbirths, alldeaths,
allpop, allmcv1, mcv1.12mo, allmcv2, allsia, first.surveillance, outbreaks, ignore.indices,
display=TRUE)
load("output-incidence.Rdat")
setwd(wd)
###################################################
### load-mortality-data
###################################################
agedist<-read.csv("input-agedist_pred.csv",header=T)
agedist.se<-read.csv("input-agedist_se.csv",header=T)
cfr1<-read.csv("input-cfr1-constant.csv",header=T,row.names=1) 
cfr2<-read.csv("input-cfr2-constant.csv",header=T,row.names=1)
cfr3<-read.csv("input-cfr3-constant.csv",header=T,row.names=1)
mcv_5<-read.csv("input-mcv1x5yrs.csv",header=T,row.names=1)
codes<-read.csv("input-gbd_Region.csv",header=T,row.names=1)
###################################################
### estimate-mortality
###################################################
setwd(paste(wd,"/single country output/",sep=""))
estimate_mortality(binary.file="output-mortality.Rdat",incidence_workspace="output-incidence.Rdat",agedist, agedist.se, cfr1,cfr2,cfr3, mcv_5, codes,ignore.indices, ITER=10000, display=TRUE)
load("output-mortality.Rdat")
setwd(wd)

###################################################
### END the fitting to data
###################################################
###################################################
### Plot Summary
###################################################
ind<-which(rownames(allcases)==country.code)
def.par <- par(no.readonly = TRUE) # save default, for resetting...

setwd(paste(wd,"/single country output/",sep=""))
if(output.figure==T)postscript(file=paste("country.code","figure.eps",sep=""),height=8,width=6,horizontal=F)
par(mar=c(2,4,2,4))
par(mfrow=c(2,1))
plot(1980:(1980+dim(allcases)[2]-1),unlist(allcases[ind,]),xlab="year",ylab="observed cases",type="l",lwd=2,col=4)
par(new=T)
plot(1980:(1980+dim(allcases)[2]-1),c(NA,unlist(CASES[ind,])),xlab=NA,ylab=NA,type="l",lwd=2,col=2,axes=F)
mtext("estimated cases",4,line=2.5)
axis(4)
par(new=T)
plot(1978:(1980+dim(allcases)[2]-1),c(1,NA,is.na(unlist(outbreaks[ind,]))),xlab=NA,ylab=NA,type="p",lwd=2,col=1,axes=F,xlim=c(1980,(1980+dim(allcases)[2]-1)))
legend(1980,.8,legend=c("observed cases","estimated cases","outbreaks"),bty="n",lty=c(1,1,NA),col=c(4,2,1),pch=c(NA,NA,1),cex=.75)
par(new=F)

plot(1980:(1980+dim(allcases)[2]-1),unlist(allmcv1[ind,]),xlab="year",ylab="MCV1",type="l",lwd=2,col=4)
par(new=T)
plot(1980:(1980+dim(allcases)[2]-1),c(NA,unlist(measles_deaths[ind,])),xlab=NA,ylab=NA,type="l",lwd=2,col=2,axes=F)
mtext("estimated deaths",4,line=2.5)
axis(4)
par(new=T)
plot(1980:(1980+dim(allcases)[2]-1),unlist(allsia[ind,]),xlab=NA,ylab=NA,type="p",lwd=2,col=1,axes=F)
legend(1980,.8*max(unlist(allsia[ind,])),legend=c("MCV1","estimated deaths","SIA coverage"),lty=c(1,1,NA),col=c(4,2,1),pch=c(NA,NA,1),cex=.75,bty="n")
par(new=F)
if(output.figure==T)dev.off()
setwd(wd)
par(def.par)#- reset to default



